### ISSUE TITLE
This repository is in violation of Unity Asset Store's terms. 

### ISSUE THREAD

**Issue by EnoxSoftware-Assets-Support** [EunhoKang/Interactive-Module-Unity#1]
Hi.

We are the developers of "OpenCVForUnity".
Your public repository contains files of a paid Unity asset that We sell on the Unity Asset Store.
Could you please change the repository attribute to private?
Or add the "OpenCVForUnity" folder path to the .gitignore file. In that case, you will need to completely remove the file from past commits as well and upload it again.

We hope that you will understand.
Thank you in advance.

Enox Software

**Comment by EunhoKang** [comment]
I delete the files of "OpenCVForUnity" from this repository.
It was just for my colledge assignment, and I just forgot to delete it.
Sorry for the mistake I made.
